DatabaseSG:
  Type: AWS::EC2::SecurityGroup
  Properties:
    VpcId: !Ref NetworkVPC
    GroupName: mytiki-lagoon-pipeline-database
    GroupDescription: Security group for the pipeline database
    SecurityGroupEgress:
      - IpProtocol: TCP
        FromPort: 5432
        ToPort: 5432
        DestinationSecurityGroupId: !Ref DagsterSG
      - IpProtocol: TCP
        FromPort: 5432
        ToPort: 5432
        DestinationSecurityGroupId: !Ref DaemonSG
      - IpProtocol: TCP
        FromPort: 5432
        ToPort: 5432
        DestinationSecurityGroupId: !Ref DbtSG
    SecurityGroupIngress:
      - IpProtocol: TCP
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId: !Ref DagsterSG
      - IpProtocol: TCP
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId: !Ref DaemonSG
      - IpProtocol: TCP
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId: !Ref DbtSG
