DatabaseSGEgress:
  Type: AWS::EC2::SecurityGroupEgress
  Properties:
    IpProtocol: tcp
    FromPort: 5432
    ToPort: 5432
    GroupId: !Ref ClusterSG
    DestinationSecurityGroupId: !Ref ClusterSG
