version = 0.1

[default.global.parameters]
stack_name = "lagoon-macro-s3-objects"
s3_bucket = "mytiki-artifacts-sar"
s3_prefix = "lagoon/macro/s3-objects"
region = "us-east-2"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [ "CAPABILITY_AUTO_EXPAND" ]
