#file: noinspection YamlFormatViolation

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  SSLCertificate:
    Type: String
    Description: The ARN of the SSL certificate to use for HTTPS traffic
  Password:
    Type: String
    Description: The password for the pipeline database. Please randomly generate this.
    NoEcho: true

Resources:
