# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: lagoon
  description: Create consumption-ready data. Aggregate raw application data in an Iceberg data lake, transform with dbt, and enforce compliance requirements. Use with mytiki.com to monetize your new data assets.
  homepage: https://mytiki.com
  topics: data, iceberg, dbt, dagster
  private: false
  has_issues: true
  has_projects: true
  has_discussions: false

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage
  - name: backend
    permission: push

environments:
  - name: production

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
