PipelineSG:
  Type: AWS::EC2::SecurityGroup
  Properties:
    VpcId: !Ref PipelineVPC
    GroupDescription: Security group for lagoon pipeline execution
    Tags:
      - Key: Name
        Value: mytiki-lagoon-pipeline
    SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8454
        ToPort: 8454
        CidrIp: 10.0.0.0/24
