version = 0.1

[default.global.parameters]
stack_name = "sar-template"
s3_bucket = "mytiki-artifacts-sar"
s3_prefix = "sar-template"
region = "us-east-2"
template_file = "out/template.yaml"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_AUTO_EXPAND"
]
image_repositories = []
parameter_overrides = []
