#file: noinspection YamlFormatViolation

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  AccessRole:
    Type: String
    Description: The ARN of the mytiki.com role that will access the lagoon

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mytiki-lagoon
    Description: Create consumption-ready data. Aggregate raw application data in an Iceberg data lake, transform with dbt, and enforce compliance requirements. Use with mytiki.com to monetize your new data assets.
    Author: mytiki
    SpdxLicenseId: AGPL-3.0-or-later
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://mytiki.com
    SemanticVersion: 0.2.5
    SourceCodeUrl: https://github.com/mytiki/lagoon
    Labels:
      - lagoon
      - iceberg
      - dbt
      - mytiki
      - data
      - productization
      - compliance
      - lake
      - monetization
      - tiki

Resources:
  Storage:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:992382831795:applications/mytiki-lagoon-storage
        SemanticVersion: 0.2.5
      Parameters:
        AccessRole: !Ref AccessRole
  Pipeline:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:992382831795:applications/mytiki-lagoon-pipeline
        SemanticVersion: 0.2.5
      Parameters:
        StorageBucket: !GetAtt Storage.Outputs.StorageBucket
  Write:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:992382831795:applications/mytiki-lagoon-write
        SemanticVersion: 0.2.5
      Parameters:
        StorageBucket: !GetAtt Storage.Outputs.StorageBucket
        PipelineWorkgroup: !GetAtt Pipeline.Outputs.PipelineWorkgroup
