#file: noinspection YamlFormatViolation

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Create consumption-ready data. Aggregate raw application data in an Iceberg data lake, transform with dbt, and enforce compliance requirements. Use with mytiki.com to monetize your new data assets.

Parameters:
  AccessRole:
    Type: String
    Description: The ARN of the mytiki.com role that will access the lagoon

Resources:

#Outputs:
#  LakeFormation:
#    Description: The managed Lake Formation instance. Use to extended LF IaC.
#    Value: !Ref LakeFormation
#    Export:
#        Name: !Sub ${AWS::StackName}-${AWS::Region}-lake-formation
