DbtTask:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ContainerDefinitions:
      - Name: mytiki-lagoon-pipeline-dbt
        Essential: true
        Image: !Ref Dbt
        PortMappings:
          - ContainerPort: 4000
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-region: !Ref AWS::Region
            awslogs-group: /ecs/mytiki-lagoon-pipeline-dbt
            awslogs-create-group: true
            awslogs-stream-prefix: ecs
        Secrets:
          - Name: "DAGSTER_PG_PASSWORD"
            ValueFrom: !Sub "${ClusterSecret}:DAGSTER_PG_PASSWORD::"
          - Name: "DAGSTER_PG_HOST"
            ValueFrom: !Sub "${ClusterSecret}:DAGSTER_PG_HOST::"
          - Name: "DAGSTER_CURRENT_IMAGE"
            ValueFrom: !Sub "${ClusterSecret}:DAGSTER_CURRENT_IMAGE::"
          - Name: "S3_BUCKET"
            ValueFrom: !Sub "${ClusterSecret}:S3_BUCKET::"
    Cpu: 256
    Memory: 512
    NetworkMode: awsvpc
    RequiresCompatibilities:
      - FARGATE
    ExecutionRoleArn: !GetAtt ClusterRole.Arn
    TaskRoleArn: !GetAtt DbtRole.Arn
    RuntimePlatform:
      CpuArchitecture: X86_64
      OperatingSystemFamily: LINUX
