DbtSGIngressHealth:
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    IpProtocol: tcp
    FromPort: 4000
    ToPort: 4000
    GroupId: !Ref DbtSG
    SourceSecurityGroupId: !Ref ClusterNLBSG
    Description: mytiki-lagoon-pipeline-internal
