DbtSGIngressDatabase:
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    IpProtocol: tcp
    FromPort: 5432
    ToPort: 5432
    GroupId: !Ref DbtSG
    SourceSecurityGroupId: !Ref DatabaseSG
    Description: mytiki-lagoon-pipeline-database
