DbtTask:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ContainerDefinitions:
      - Name: mytiki-lagoon-pipeline-dbt
        Essential: true
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${StorageBucket}:dbt-example
        PortMappings:
          - ContainerPort: 4000
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-region: !Ref AWS::Region
            awslogs-group: /ecs/mytiki-lagoon-pipeline-dbt
            awslogs-create-group: true
            awslogs-stream-prefix: ecs
        Environment:
          - Name: "DAGSTER_PG_PASSWORD"
            Value: !Ref Password
          - Name: "DAGSTER_PG_HOST"
            Value: !GetAtt Database.Endpoint.Address
          - Name: "DAGSTER_CURRENT_IMAGE"
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${StorageBucket}:dbt-example
    Cpu: 512
    Memory: 2048
    NetworkMode: awsvpc
    RequiresCompatibilities:
      - FARGATE
    ExecutionRoleArn: !GetAtt ClusterRole.Arn
    TaskRoleArn: !GetAtt DbtRole.Arn
    RuntimePlatform:
      CpuArchitecture: X86_64
      OperatingSystemFamily: LINUX
