DbtRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: mytiki-lagoon-pipeline-dbt
    Description: Lagoon ECS role assumed by dbt tasks
    AssumeRolePolicyDocument:
      Version: 2008-10-17
      Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ecs-tasks.amazonaws.com
    Policies:
      - PolicyName: S3
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: s3:*
              Resource:
                - !Sub arn:aws:s3:::${StorageBucket}
                - !Sub arn:aws:s3:::${StorageBucket}/*
      - PolicyName: Athena
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: athena:*
              Resource: !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${PipelineAthenaWorkgroup}
      - PolicyName: Glue
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: glue:*
              Resource:
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*
