DaemonTG:
  Type: AWS::ElasticLoadBalancingV2::TargetGroup
  Properties:
    Port: 4001
    Protocol: TCP
    VpcId: !Ref NetworkVPC
    TargetType: ip
    HealthCheckProtocol: HTTP
    HealthCheckPort: 4001
    HealthCheckPath: /healthcheck
