DaemonService:
  Type: AWS::ECS::Service
  DependsOn: DaemonListener
  Properties:
    Cluster: !GetAtt Cluster.Arn
    DeploymentConfiguration:
      MinimumHealthyPercent: 50
    DeploymentController:
      Type: ECS
    DesiredCount: 1
    HealthCheckGracePeriodSeconds: 30
    LaunchType: FARGATE
    LoadBalancers:
      - ContainerName: mytiki-lagoon-pipeline-daemon
        ContainerPort: 4001
        TargetGroupArn: !Ref DaemonTG
    NetworkConfiguration:
      AwsvpcConfiguration:
        AssignPublicIp: ENABLED
        SecurityGroups:
          - !GetAtt DaemonSG.GroupId
        Subnets:
          - !Ref NetworkSubnetA
          - !Ref NetworkSubnetB
    PlatformVersion: LATEST
    ServiceName: mytiki-lagoon-pipeline-daemon
    TaskDefinition: !GetAtt DaemonTask.TaskDefinitionArn
