DaemonSGEgressNLB:
  Type: AWS::EC2::SecurityGroupEgress
  Properties:
    IpProtocol: tcp
    FromPort: 4000
    ToPort: 4000
    GroupId: !Ref DaemonSG
    DestinationSecurityGroupId: !Ref ClusterNLBSG
    Description: mytiki-lagoon-pipeline-internal
