DaemonSGIngressHealth:
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    IpProtocol: tcp
    FromPort: 4001
    ToPort: 4001
    GroupId: !Ref DaemonSG
    SourceSecurityGroupId: !Ref ClusterNLBSG
    Description: mytiki-lagoon-pipeline-internal
