DaemonSG:
  Type: AWS::EC2::SecurityGroup
  Properties:
    VpcId: !Ref NetworkVPC
    GroupName: mytiki-lagoon-pipeline-daemon
    GroupDescription: Security group for the mytiki-lagoon pipeline daemon service
    SecurityGroupEgress:
      - IpProtocol: TCP
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
