PipelineExecutionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: mytiki-lagoon-pipeline-execution
    Description: Lagoon ECS execution role for launching pipeline tasks
    AssumeRolePolicyDocument:
      Version: 2008-10-17
      Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ecs-tasks.amazonaws.com
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    Policies:
      - PolicyName: Log
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: logs:CreateLogGroup
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/mytiki-lagoon-pipeline:log-stream:"
