ClusterALB:
  Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  Properties:
    Type: application
    Name: mytiki-lagoon-pipeline-public
    Scheme: internet-facing
    Subnets:
      - !Ref NetworkSubnetA
      - !Ref NetworkSubnetB
    SecurityGroups:
      - !Ref ClusterALBSG

