ClusterNLB:
  Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  Properties:
    Type: network
    Name: mytiki-lagoon-pipeline-internal
    Scheme: internal
    Subnets:
      - !Ref NetworkSubnetA
      - !Ref NetworkSubnetB
    SecurityGroups:
      - !Ref ClusterNLBSG
