WriteFunction:
  Type: AWS::Serverless::Function
  Properties:
    Description: Writes raw data files to Iceberg compatible tables
    FunctionName: !Sub ${AWS::StackName}-write
    CodeUri: ../src/write/function
    Handler: com.mytiki.lagoon.write.Handler::handleRequest
    Runtime: java21
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 30
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: TRACE
      SystemLogLevel: DEBUG
    Environment:
      Variables:
        AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-sqs-handler
        ICEBERG_WAREHOUSE: !Sub s3://${StorageBucket}
    ReservedConcurrentExecutions: 1
    PropagateTags: true
    Events:
      SQSEvent:
        Type: SQS
        Properties:
          Enabled: true
          FunctionResponseTypes:
            - ReportBatchItemFailures
          BatchSize: 10
          Queue: !GetAtt WriteQueue.Arn
    Policies:
      - S3CrudPolicy:
          BucketName: !Ref StorageBucket
      - Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - glue:GetTable
              - glue:GetTables
              - glue:UpdateTable
            Resource:
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Resource: "*"
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:901920570463:layer:aws-otel-java-wrapper-amd64-ver-1-30-0:1
