version = 0.1

[default.global.parameters]
stack_name = "lagoon-prepare"
s3_bucket = "mytiki-artifacts-sar"
s3_prefix = "lagoon/prepare"
region = "us-east-2"
template_file = "out/template.yml"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [ "CAPABILITY_AUTO_EXPAND" ]
