#file: noinspection YamlFormatViolation

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "mytiki-lagoon | prepare module | automate conversion of raw data from popular formats for Iceberg compatibility"

Parameters:
  StorageBucket:
    Type: String
    Description: The S3 bucket name for the Lagoon

Resources:
