ClusterSecret:
  Type: AWS::SecretsManager::Secret
  Properties:
    Description: "Secrets shared amongst the pipeline cluster"
    Name: mytiki-lagoon-pipeline
    SecretString: !Sub |
      {
        "DAGSTER_PG_PASSWORD": "${Password}",
        "DAGSTER_PG_HOST": "${Database.Endpoint.Address}",
        "DAGSTER_CURRENT_IMAGE": "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${StorageBucket}:dbt-example",
        "S3_BUCKET": "${StorageBucket}",
        "DAGSTER_GRPC_SERVER_HOST": "${ClusterNLB.DNSName}"
      }
