version = 0.1

[default.global.parameters]
stack_name = "lagoon-pipeline-agent"
s3_bucket = "mytiki-sam-deploy-sandbox-mike-us-east-2"
s3_prefix = "lagoon/pipeline/agent"
region = "us-east-2"
template_file = "out/template.yml"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_AUTO_EXPAND",
    "CAPABILITY_NAMED_IAM"
]
