CodeBuildRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: mytiki-lagoon-pipeline-deploy-codebuild
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: S3
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetBucketVersioning
                - s3:GetBucketAcl
                - s3:GetBucketLocation
                - s3:PutObject
              Resource:
                - !Sub arn:aws:s3:::${StorageBucket}
                - !Sub arn:aws:s3:::${StorageBucket}/*
      - PolicyName: CodeBuild
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - codebuild:CreateReportGroup
                - codebuild:CreateReport
                - codebuild:UpdateReport
                - codebuild:BatchPutTestCases
                - codebuild:BatchPutCodeCoverages
              Resource:
                - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/{CodeBuild}-*
      - PolicyName: ECR
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ecr:GetAuthorizationToken
                - ecr:BatchCheckLayerAvailability
                - ecr:GetDownloadUrlForLayer
                - ecr:GetRepositoryPolicy
                - ecr:DescribeRepositories
                - ecr:ListImages
                - ecr:DescribeImages
                - ecr:BatchGetImage
                - ecr:GetLifecyclePolicy
                - ecr:GetLifecyclePolicyPreview
                - ecr:ListTagsForResource
                - ecr:DescribeImageScanFindings
                - ecr:InitiateLayerUpload
                - ecr:UploadLayerPart
                - ecr:CompleteLayerUpload
                - ecr:PutImage
              Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${StorageBucket}
            - Effect: Allow
              Action: ecr:GetAuthorizationToken
              Resource: "*"
