SfnRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: mytiki-lagoon-load-sfn
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: states.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: Glue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - glue:StartJobRun
                - glue:GetJobRun
                - glue:GetJobRuns
                - glue:BatchStopJobRun
              Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${DataGlueJob}
      - PolicyName: S3
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "s3:Get*"
                - "s3:List*"
                - "s3:*Object*"
              Resource: !Sub arn:aws:s3:::${StorageBucket}/load/*
