Database:
  Type: AWS::RDS::DBInstance
  Properties:
    DBName: dagster
    AllocatedStorage: 25
    AutoMinorVersionUpgrade: true
    BackupRetentionPeriod: 30
    DBInstanceIdentifier: pipeline
    DBInstanceClass: db.t4g.micro
    Engine: postgres
    EngineVersion: 16.2
    MasterUsername: dagster
    MasterUserPassword: !Ref Password
    PubliclyAccessible: false
    StorageEncrypted: true
    MaxAllocatedStorage: 250
    CACertificateIdentifier: rds-ca-ecc384-g1
    DBSubnetGroupName: !Ref DatabaseSubnet
    VPCSecurityGroups:
      - !GetAtt DatabaseSG.GroupId
