#file: noinspection YamlFormatViolation

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "mytiki-lagoon | pipline module | execute and automate data transformation with dbt pipelines and dagster orchestration"

Parameters:
  StorageBucket:
    Type: String
    Description: The S3 bucket name for the Lagoon
  SSLCertificate:
    Type: String
    Description: The ARN of the SSL certificate to use for HTTPS traffic
  Password:
    Type: String
    Description: The password for the pipeline database. Please randomly generate this.
    NoEcho: true
  Dagster:
    Type: String
    Description: The version of the dagster image to use for the pipeline
    Default: 0.3.29
  Dbt:
    Type: String
    Description: "The URI:tag of corresponding to the dbt image to use in the pipeline"
    Default: public.ecr.aws/mytiki/mytiki-lagoon:dbt-example-0.3.29

Resources:

Outputs:
  PipelineWorkgroup:
    Description: The Athena workgroup for the Lagoon
    Value: !Ref PipelineAthenaWorkgroup
    Export:
      Name: mytiki-lagoon-pipeline-athena
