WebserverTask:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ContainerDefinitions:
      - Name: dagster-webserver
        Essential: true
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/dagster:latest-webserver
        PortMappings:
          - ContainerPort: 3000
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-region: !Ref AWS::Region
            awslogs-group: /ecs/dagster-webserver
            awslogs-create-group: true
            awslogs-stream-prefix: ecs
    Cpu: 512
    Memory: 2048
    NetworkMode: awsvpc
    RequiresCompatibilities:
      - FARGATE
    ExecutionRoleArn: !GetAtt ClusterExecutionRole.Arn
    TaskRoleArn: !GetAtt WebserverRole.Arn
    RuntimePlatform:
      CpuArchitecture: X86_64
      OperatingSystemFamily: LINUX
