WebserverDNS:
  Type: AWS::Route53::RecordSet
  Properties:
    HostedZoneId: Z09413743UY2G8UHP9J3G
    Name: pipeline.mike.mytiki.com
    Type: A
    AliasTarget:
      DNSName: !GetAtt WebserverALB.DNSName
      HostedZoneId: !GetAtt WebserverALB.CanonicalHostedZoneID
      EvaluateTargetHealth: false
