WriteQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: mytiki-lagoon-write.fifo
    ContentBasedDeduplication: true
    DeduplicationScope: messageGroup
    FifoQueue: true
    FifoThroughputLimit: perMessageGroupId
    MessageRetentionPeriod: 604800
    RedrivePolicy:
      deadLetterTargetArn: !ImportValue mytiki-lagoon-log-queue
      maxReceiveCount: 5
