WriteQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: !Sub ${AWS::StackName}.fifo
    ContentBasedDeduplication: true
    DeduplicationScope: messageGroup
    FifoQueue: true
    FifoThroughputLimit: perMessageGroupId
    MessageRetentionPeriod: 604800
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt WriteDlq.Arn
      maxReceiveCount: 5
