WriteFunction:
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: arn:aws:serverlessrepo:us-east-2:992382831795:applications/mytiki-lagoon-write-function
      SemanticVersion: 0.2.2
    Parameters:
      StorageBucket: !Ref StorageBucket
      PipelineWorkgroup: !Ref PipelineWorkgroup
      WriteDependencies: !GetAtt WriteLayer.Outputs.WriteLayer
