WriteFunction:
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: arn:aws:serverlessrepo:us-east-2:992382831795:applications/mytiki-lagoon-write-function
      SemanticVersion: 0.3.7
    Parameters:
      StorageBucket: !Ref StorageBucket
      PipelineWorkgroup: !Ref PipelineWorkgroup
      WriteDependenciesAws: !GetAtt WriteLayerAws.Outputs.WriteLayer
      WriteDependenciesIceberg: !GetAtt WriteLayerIceberg.Outputs.WriteLayer
      WriteQueue: !GetAtt WriteQueue.Arn
