WriteFunction:
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: arn:aws:serverlessrepo:us-east-2:992382831795:applications/mytiki-lagoon-write-function
      SemanticVersion: 0.2.0
    Parameters:
      Bucket: !Ref StorageBucket
      Workgroup: !Ref PipelineWorkgroup
      Dependencies: !GetAtt WriteLayer.Outputs.WriteLayer
