WriteDlq:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: !Sub ${AWS::StackName}-dlq.fifo
    ContentBasedDeduplication: true
    DeduplicationScope: messageGroup
    FifoQueue: true
    FifoThroughputLimit: perMessageGroupId
    MessageRetentionPeriod: 604800
    RedriveAllowPolicy:
      redrivePermission: byQueue
      sourceQueueArns:
        - !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}.fifo
