NetworkSubnetA:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId: !Ref NetworkVPC
    CidrBlock: 10.0.1.0/24
    AvailabilityZone: !Sub ${AWS::Region}a
    Tags:
      - Key: Name
        Value: mytiki-lagoon-pipeline-subnet-a
