StorageBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub mytiki-lagoon-${AWS::AccountId}-${AWS::Region}
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    NotificationConfiguration:
      EventBridgeConfiguration:
        EventBridgeEnabled: true
