DataGlueJob:
  Type: AWS::Glue::Job
  Properties:
    Name: mytiki-lagoon-load-data
    Description: Normalize and load data files into the Lagoon Iceberg data lake tables
    Timeout: 90
    GlueVersion: 4.0
    WorkerType: G.1X
    NumberOfWorkers: 10
    MaxRetries: 5
    ExecutionProperty:
      MaxConcurrentRuns: 100
    Command:
      Name: glueetl
      ScriptLocation: !Sub s3://${StorageBucket}/assets/deploy/load/${Version}/glue-script.py
    DefaultArguments:
      "--TempDir": !Sub s3://${StorageBucket}/tmp/load
      "--datalake-formats": "iceberg"
      "--conf": !Sub >
        spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
        --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog
        --conf spark.sql.catalog.glue_catalog.warehouse=s3://${StorageBucket}/stg/
        --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
        --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
    Role: !GetAtt DataGlueRole.Arn
    ExecutionClass: FLEX

