PipelineAthenaWorkgroup:
  Type: AWS::Athena::WorkGroup
  Properties:
    Name: mytiki-lagoon
    Description: Workgroup for the lagoon pipelines
    State: ENABLED
    RecursiveDeleteOption: true
    WorkGroupConfiguration:
      ResultConfiguration:
        OutputLocation: !Sub s3://${StorageBucket}/queries/
      EnforceWorkGroupConfiguration: true
      EngineVersion:
        SelectedEngineVersion: Athena engine version 3
