StepFunctionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: mytiki-lagoon-prepare-step-role
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: states.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: glue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - glue:StartJobRun
                - glue:GetJobRun
                - glue:GetJobRuns
                - glue:BatchStopJobRun
              Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${PrepareGlueJob}
      - PolicyName: sqs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: !ImportValue mytiki-lagoon-log-queue
      - PolicyName: s3
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "s3:Get*"
                - "s3:List*"
                - "s3:*Object*"
              Resource: !Sub arn:aws:s3:::${StorageBucket}/prepare/*
