EventRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: mytiki-lagoon-prepare-event-role
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: states
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: states:StartExecution
              Resource: !Ref PrepareStepFunction
