WriteEventRule:
  Type: AWS::Events::Rule
  Properties:
    Name: mytiki-lagoon-write
    State: ENABLED
    Targets:
      - Arn: !GetAtt EventQueue.Arn
        Id: !GetAtt EventQueue.QueueName
    EventPattern:
      source:
        - aws.s3
      detail-type:
        - Object Created
      detail:
        bucket:
          name:
            - !Ref StorageBucket
        object:
          key:
            - wildcard: load/*
