#file: noinspection YamlFormatViolation

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mytiki-lagoon-macro
    Description: Sub-component of the mytiki.com Lagoon application. Deploys the CloudFormation macros.
    Author: mytiki
    SpdxLicenseId: AGPL-3.0-or-later
    LicenseUrl: ../../LICENSE
    ReadmeUrl: ../../README.md
    HomePageUrl: https://mytiki.com
    SemanticVersion: 0.3.8
    SourceCodeUrl: https://github.com/mytiki/lagoon
    Labels:
      - lagoon
      - mytiki
      - component

Resources:
  S3Objects:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:992382831795:applications/mytiki-lagoon-macro-s3-objects
        SemanticVersion: 0.3.8
