DagsterSGIngressApp:
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    IpProtocol: tcp
    FromPort: 3000
    ToPort: 3000
    GroupId: !Ref DagsterSG
    SourceSecurityGroupId: !Ref ClusterALBSG
    Description: mytiki-lagoon-pipeline-dagster-app
