DagsterService:
  Type: AWS::ECS::Service
  DependsOn: DagsterListenerHTTPS
  Properties:
    Cluster: !GetAtt Cluster.Arn
    DeploymentConfiguration:
      MinimumHealthyPercent: 50
    DeploymentController:
      Type: ECS
    DesiredCount: 1
    HealthCheckGracePeriodSeconds: 30
    LaunchType: FARGATE
    LoadBalancers:
      - ContainerName: mytiki-lagoon-pipeline-dagster
        ContainerPort: 3000
        TargetGroupArn: !Ref DagsterTG
    NetworkConfiguration:
      AwsvpcConfiguration:
        AssignPublicIp: ENABLED
        SecurityGroups:
          - !GetAtt DagsterSG.GroupId
        Subnets:
          - !Ref NetworkSubnetA
          - !Ref NetworkSubnetB
    PlatformVersion: LATEST
    ServiceName: mytiiki-lagoon-pipeline-dagster
    TaskDefinition: !GetAtt DagsterTask.TaskDefinitionArn
