version: 2

sources:
  - name: mytiki
    description: Testing dbt+dagster
    database: awsdatacatalog
    schema: mytiki
    loader: lagoon
    loaded_at_field: _etl_loaded_at
    tables:
      - name: test
        description: >
          TESTYWESTY

        columns:
          - name: userid
            description: Opaque ID that uniquely identifies a user
            # tests:
            #   - not_null

          - name: receiptid
            description: Unique ID that can be used to group records
            # tests:
            #   - not_null

          - name: receipt_date
            description: The data of the receipt in YYYY-MM-DD format
            # tests:
            #   - not_null

          - name: merchant_name
            description: The name of the merchant

          - name: merchant_address
            description: The street address of the merchant

          - name: merchant_city
            description: The city of the merchant

          - name: merchant_state
            description: The 2-letter abbreviation for the merchant's state

          - name: merchant_zip
            description: The merchant's zip code

          - name: channel
            description: The purchase channel (online, in-store, etc.)

          - name: amount
            description: The total amount for the receipt

          - name: brand
            description: The brand name for a lineitem

          - name: product_name
            description: The name of the product

          - name: product_description
            description: A description of the product

          - name: quantity
            description: The quantity of a lineitem

          - name: unit_price
            description: The individual unit price for the lineitem

          - name: total_price
            description: The total lineitem price based on quantity

          - name: category_level1
            description: Product category level 1

          - name: category_level2
            description: Product category level 2

          - name: category_level3
            description: Product category level 3

          - name: size
            description: A string representing the size of the product

          - name: upc
            description: The UPC code of the product

          - name: _etl_loaded_at
            description: The timestamp of when the record was loaded into the Lagoon
