StorageAccessPoint:
  Type: AWS::S3::AccessPoint
  Properties:
    Bucket: !Ref StorageBucket
    BucketAccountId: !Ref AWS::AccountId
    Name: mytiki
    Policy:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            AWS: !GetAtt StorageAccessRole.Arn
          Action:
            - s3:GetObject
            - s3:GetObjectVersion
          Resource:
            - !Sub arn:aws:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/mytiki/object/prd/*
        - Effect: Allow
          Principal:
            AWS: !GetAtt StorageAccessRole.Arn
          Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:PutObject
            - s3:DeleteObject
            - s3:DeleteObjectVersion
            - s3:ListMultipartUploadParts
            - s3:AbortMultipartUpload
          Resource:
            - !Sub arn:aws:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/mytiki/object/trail/*
            - !Sub arn:aws:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/mytiki/object/assets/*
            - !Sub arn:aws:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/mytiki/object/load/mytiki/*
        - Effect: Allow
          Principal:
            AWS: !GetAtt StorageAccessRole.Arn
          Action: s3:ListBucket
          Resource: !Sub arn:aws:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/mytiki
