StorageAccessRole:
  Type: AWS::IAM::Role
  DependsOn: StorageBucket
  Properties:
    RoleName: !Sub ${AWS::StackName}-mytiki
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref AccessRole
          Action: sts:AssumeRole
    Policies:
      - PolicyName: mytiki
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
              Resource:
                - !Sub s3://${StorageBucket}/prd/*
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:PutObject
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
              Resource:
                - !Sub s3://${StorageBucket}/trail/*
                - !Sub s3://${StorageBucket}/assets/*
                - !Sub s3://${StorageBucket}/load/mytiki/*
            - Effect: Allow
              Action: s3:ListBucket
              Resource: !Sub s3://${StorageBucket}
