StorageBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub mytiki-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    NotificationConfiguration:
      QueueConfigurations:
        - Event: s3:ObjectCreated:*
          Queue: !GetAtt WriteQueue.Arn
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: load/
                - Name: suffix
                  Value: .parquet
