name: 'mytiki_lagoon'

config-version: 2
version: '0.1'

profile: 'lagoon'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

flags:
  use_colors_file: False
  send_anonymous_usage_stats: False

seeds:
  us_states:
    +seed_by_insert: True
    +native_drop: True
    +column_types:
      pop_2020: integer
      area_sq_mi: real

models:
  mytiki:
    materialized: table
