lagoon:
  target: prd
  outputs:
    prd:
      type: athena
      threads: 24
      region_name: us-east-2
      database: awsdatacatalog
      schema: prd
      work_group: mytiki-lagoon
      s3_data_dir: s3://mytiki-lagoon-590184107666-us-east-2/prd/
      s3_staging_dir: s3://mytiki-lagoon-590184107666-us-east-2/queries
      s3_tmp_table_dir: s3://mytiki-lagoon-590184107666-us-east-2/tmp
