name: "Publish"

on:
  push:
#    branches: [ "main" ]

env:
  AWS_REGION: "us-east-2"

jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y xmlstarlet
          cargo install cargo-zigbuild
          rustup target add x86_64-unknown-linux-musl

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_IDENTITY_ID }}:role/GitHubOidc
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Assume Artifacts Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ARTIFACTS_ID }}:role/GitHubEcrPublish
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
          role-chaining: true

      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: fix/restructure-deployment
      #          branch: main

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Publish Application
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: h8w5d6c4
          REPOSITORY: mytiki-lagoon
          IMAGE_TAG: ${{ steps.semver.outputs.nextStrict}}
        run: |
          make publish version=$IMAGE_TAG repository=$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY

  Release:
    needs: Publish
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.semver.outputs.nextStrict }} -m "Release ${{ steps.semver.outputs.nextStrict }}"
          git push origin ${{ steps.semver.outputs.nextStrict }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.semver.outputs.nextStrict }} \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ steps.semver.outputs.nextStrict }}" \
              --generate-notes
