name: "Publish"

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "us-east-2"

jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_IDENTITY_ID }}:role/GitHubOidc
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Assume Artifacts Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ARTIFACTS_ID }}:role/GitHubSarPublish
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
          role-chaining: true

      - name: Build Application
        run: |
          make compile
          make build

      - name: Publish Artifacts
        run: |
          aws s3 cp src/write/function/target/lambda/write-function.jar s3://mytiki-artifacts-sar/lagoon/packages/write-function.jar
          aws s3 cp src/write/layer/target/lambda/layer-content.zip s3://mytiki-artifacts-sar/lagoon/packages/layer-content.zip

      - name: Publish Application
        id: publish
        run: |
          sam package --output-template-file .aws-sam/packaged.yaml
          result=$(sam publish --template .aws-sam/packaged.yaml)
          echo "$result"
          arn=$(echo "$result" | grep -oP 'arn:aws:serverlessrepo:[^ ]+' | head -n 1)
          arn_clean=$(echo "$arn" | sed 's/[\"'\'']//g' | tr -d '[:space:]')
          echo "application_arn=$arn_clean" >> "$GITHUB_OUTPUT"

      - name: Share Application
        run: |
          echo "Application ARN: ${{ steps.publish.outputs.application_arn }}"
          aws serverlessrepo put-application-policy \
          --application-id ${{ steps.publish.outputs.application_arn }} \
          --statements Principals=*,PrincipalOrgIDs=${{ secrets.AWS_ORG_ID }},Actions=Deploy,UnshareApplication
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

  Release:
    needs: Publish
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.semver.outputs.nextStrict }} -m "Release ${{ steps.semver.outputs.nextStrict }}"
          git push origin ${{ steps.semver.outputs.nextStrict }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.semver.outputs.nextStrict }} \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ steps.semver.outputs.nextStrict }}" \
              --generate-notes
